In [3]:
import numpy as np
import pandas as pd

In [4]:
np.random.rand(3,2)
np.zeros([3,2,1])
np.ones([3,2,1])

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [5]:
y = np.random.rand(3,2)
print(y)
z = np.array(y,dtype='float64')
print(z)

[[0.80352949 0.18738035]
 [0.63478173 0.7626858 ]
 [0.84987096 0.05078665]]
[[0.80352949 0.18738035]
 [0.63478173 0.7626858 ]
 [0.84987096 0.05078665]]


In [6]:
timeend = np.datetime64("2022-01-01")
timestart = np.datetime64("2000-01-01")
diff = timeend-timestart
print(diff)

delta_days = np.datetime64("2022-01-01")-np.datetime64("2000-01-01")

8036 days


In [7]:
a = np.random.rand(3,3)
b = a[:,0].copy() # get first column as a row vector!
c = a[:,[0]].copy() # get first column as a column vector!

print(a)
print(b)


[[0.07948619 0.20766139 0.65353421]
 [0.68361879 0.50410072 0.93770716]
 [0.92299235 0.03908524 0.68391311]]
[0.07948619 0.68361879 0.92299235]


In [8]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
n1 = np.argwhere(x)
n2 = np.nonzero(x)
print(n1)
print(n2)

x[n1]

[[0 0]
 [1 1]
 [2 0]
 [2 1]]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))


array([[[3, 0, 0],
        [3, 0, 0]],

       [[0, 4, 0],
        [0, 4, 0]],

       [[5, 6, 0],
        [3, 0, 0]],

       [[5, 6, 0],
        [0, 4, 0]]])

In [10]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
m=X.flatten()
n=X.ravel()

print(m)
print(n)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [15]:
test=np.random.rand(9,9)
test[np.ix_([1,2,8],[3,4,7])]

array([[0.08812401, 0.22942693, 0.76652041],
       [0.52547035, 0.10917958, 0.79803472],
       [0.60121891, 0.27752016, 0.75946202]])

In [25]:
a = np.arange(0,10,1)
b = np.arange(10,20,1)
#print(a,b)

# concatenation row and column 

r = np.r_[a,b]
print(r)
c = np.c_[a,b]
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [26]:
test

array([[0.51773609, 0.73952696, 0.0512372 , 0.67454136, 0.80787881,
        0.84620919, 0.93676159, 0.76141532, 0.79275273],
       [0.6235471 , 0.74193051, 0.75459319, 0.08812401, 0.22942693,
        0.75419074, 0.06538121, 0.76652041, 0.33860842],
       [0.20408488, 0.2379566 , 0.92442753, 0.52547035, 0.10917958,
        0.09701733, 0.75311374, 0.79803472, 0.3413126 ],
       [0.63637949, 0.19092108, 0.40492089, 0.92513823, 0.22886545,
        0.80577167, 0.45428812, 0.17694612, 0.49139047],
       [0.13970479, 0.92688532, 0.56780354, 0.79691443, 0.62290678,
        0.34487844, 0.41005904, 0.0416624 , 0.7924787 ],
       [0.39077659, 0.46011064, 0.01981903, 0.31699273, 0.02847661,
        0.19432527, 0.26771377, 0.69962996, 0.82070812],
       [0.85670409, 0.75823159, 0.17451408, 0.0541317 , 0.12807091,
        0.27894388, 0.9264224 , 0.25871553, 0.39220355],
       [0.19181691, 0.28501479, 0.35648184, 0.09135537, 0.68036404,
        0.90902867, 0.21256886, 0.35587645, 0.62426871],


In [27]:
test[(np.nonzero(test>0.5)[0],np.nonzero(test>0.5)[1])]


array([0.51773609, 0.73952696, 0.67454136, 0.80787881, 0.84620919,
       0.93676159, 0.76141532, 0.79275273, 0.6235471 , 0.74193051,
       0.75459319, 0.75419074, 0.76652041, 0.92442753, 0.52547035,
       0.75311374, 0.79803472, 0.63637949, 0.92513823, 0.80577167,
       0.92688532, 0.56780354, 0.79691443, 0.62290678, 0.7924787 ,
       0.69962996, 0.82070812, 0.85670409, 0.75823159, 0.9264224 ,
       0.68036404, 0.90902867, 0.62426871, 0.83468463, 0.60121891,
       0.50107245, 0.75946202, 0.69656472])

In [28]:
test[np.nonzero(test>0.5)]


array([0.51773609, 0.73952696, 0.67454136, 0.80787881, 0.84620919,
       0.93676159, 0.76141532, 0.79275273, 0.6235471 , 0.74193051,
       0.75459319, 0.75419074, 0.76652041, 0.92442753, 0.52547035,
       0.75311374, 0.79803472, 0.63637949, 0.92513823, 0.80577167,
       0.92688532, 0.56780354, 0.79691443, 0.62290678, 0.7924787 ,
       0.69962996, 0.82070812, 0.85670409, 0.75823159, 0.9264224 ,
       0.68036404, 0.90902867, 0.62426871, 0.83468463, 0.60121891,
       0.50107245, 0.75946202, 0.69656472])

In [31]:
a = np.arange(9).reshape((3,3))
print(a)
a.flatten()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.ones((3, 4)), np.zeros((3, 4))

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [39]:
a=np.eye(3)
np.diag(a)
np.diag(a, 1)


array([0., 0.])

In [40]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [41]:
np.mgrid[0:3,0:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [42]:
np.ix_([1,3],[8,9])

(array([[1],
        [3]]),
 array([[8, 9]]))

In [68]:
q = np.random.rand(5,5)
#get rows 0,2 and columns 3,4

w = q[np.ix_([0,2],[3,4])]
e = q[(np.array([0,2])[:,np.newaxis],np.r_[3,4])]
r = q[np.array([[0],[2]]),np.array([3,4])]

print(w)
print(e)
print(r)

[[0.51971681 0.5462111 ]
 [0.70223493 0.02760431]]
[[0.51971681 0.5462111 ]
 [0.70223493 0.02760431]]
[[0.51971681 0.5462111 ]
 [0.70223493 0.02760431]]


In [55]:
np.ix_([0,2],[3,4])

ValueError: Cross index must be 1 dimensional

In [66]:
np.array([[0],[2]])

array([[0],
       [2]])

In [54]:
np.array([0,2])[:,np.newaxis]

array([[0],
       [2]])

In [72]:
q = np.random.rand(5,5)
print(q)
q[[[2],[4]],[2,4]]

[[0.94173081 0.26463704 0.56306332 0.81968814 0.64703775]
 [0.80530326 0.42344663 0.47709193 0.69560571 0.54086188]
 [0.14691411 0.5885195  0.03954709 0.17606853 0.01601906]
 [0.40242934 0.78252023 0.59872204 0.23354021 0.58601665]
 [0.9099915  0.62260419 0.95360803 0.82249647 0.35512673]]


array([[0.03954709, 0.01601906],
       [0.95360803, 0.35512673]])

In [75]:
a = np.random.rand(2,3)
np.tile(a, (2, 3))

array([[0.2182233 , 0.3218257 , 0.40169982, 0.2182233 , 0.3218257 ,
        0.40169982, 0.2182233 , 0.3218257 , 0.40169982],
       [0.49784672, 0.74731682, 0.63594195, 0.49784672, 0.74731682,
        0.63594195, 0.49784672, 0.74731682, 0.63594195],
       [0.2182233 , 0.3218257 , 0.40169982, 0.2182233 , 0.3218257 ,
        0.40169982, 0.2182233 , 0.3218257 , 0.40169982],
       [0.49784672, 0.74731682, 0.63594195, 0.49784672, 0.74731682,
        0.63594195, 0.49784672, 0.74731682, 0.63594195]])

In [81]:
print(np.c_[0,1,2])
print(np.c_[0:3])

[[0 1 2]]
[[0]
 [1]
 [2]]


In [93]:
a = np.ones((3,3))
b = np.zeros((3,3))
c = np.concatenate((a,b),axis = 0)
d = np.r_[a,b]
e = np.vstack((a,b))
f = np.row_stack([a,b])
print(c)
print(d)
print(e)
print(f)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [95]:
f.std(axis=0)

array([0.5, 0.5, 0.5])

In [100]:
np.maximum(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# try matrix inversion